services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: calcpass
      POSTGRES_DB: calcdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calcdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:calcpass@db:5432/calcdb
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:8.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      db:
        condition: service_healthy
