# .github/docker-compose.ci.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calcdb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../app     # âœ… FIX: go up one level
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/calcdb
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:8.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
